name: Upload Beta Release (1GP)
on:
  push:
    branches:    
      - 'main'
jobs:
  upload-beta:
    uses: SFDO-Community/standard-workflows/.github/workflows/beta-2gp.yml@main
    secrets:
      dev-hub-auth-url: '${{ secrets.DEV_HUB_AUTH_URL }}'