on:
    workflow_dispatch:
env:
    CUMULUSCI_KEYCHAIN_CLASS: cumulusci.core.keychain.EnvironmentProjectKeychain
    CUMULUSCI_SERVICE_github: ${{ secrets.CUMULUSCI_SERVICE_github }}
      
jobs:
    beta-release:
      name: "Upload Production Release (2GP)"
      runs-on: ubuntu-latest
      steps:
        # Install Salesforce CLI
        - name: 'Install Salesforce CLI'
          run: |
              npm install @salesforce/cli --location=global
              nodeInstallPath=$(npm config get prefix)
              echo "$nodeInstallPath/bin" >> $GITHUB_PATH
              sf --version
      
        # Checkout the source code
        - name: 'Checkout source code'
          uses: actions/checkout@v3
            
        # Store secret for dev hub
        - name: 'Populate auth file with DEV_HUB_AUTH_URL secret'
          shell: bash
          run: |
              echo ${{ secrets.DEV_HUB_AUTH_URL}} > ./SFDX_AUTH_URL.txt
              secretFileSize=$(wc -c "./SFDX_AUTH_URL.txt" | awk '{print $1}')
              if [ $secretFileSize == 1 ]; then
                   echo "Missing SFDX_AUTH_URL secret. Is this workflow running on a fork?";
                   exit 1;
              fi
      
        # Authenticate dev hub
        - name: 'Authenticate Dev Hub'
          run: sf org login sfdx-url -f ./SFDX_AUTH_URL.txt -a devhub -d
      
        # Remove auth file
        - name: 'Remove auth file'
          run: rm -f ./SFDX_AUTH_URL.txt
      
        # Install Python
        - name: Set up Python
          uses: actions/setup-python@v3
          with:
              python-version: '3.10'
        # Install CumuulusCI
        - name: Install CumulusCI
          run: |
              python -m pip install -U pip
              pip install cumulusci

        - name: Promote and release to production
          run: |
              cci flow run release_2gp_production 