on:
    workflow_dispatch:
        
  jobs:
    upload-production-release-1gp:
      name: "Upload Production Release (1GP)"
      uses: SFDO-Community/standard-workflows/.github/workflows/production-2gp.yml@main
      secrets:
        dev-hub-auth-url: '${{ secrets.DEV_HUB_AUTH_URL }}'